# Generated by Django 6.0 on 2026-04-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("restaurant", "Restaurants"),
                    ("cafe", "Cafes & Coffee"),
                    ("fast_food", "Fast Food"),
                    ("dessert", "Desserts & Sweets"),
                    ("bakery", "Bakery"),
                    ("juice", "Juice & Smoothies"),
                    ("food_truck", "Food Trucks"),
                    ("culture", "Culture"),
                    ("outdoor", "Outdoor"),
                    ("shopping", "Shopping"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
