# Generated by Django 6.0 on 2026-04-22 09:59

import django.core.validators
from django.db import migrations, models


LEGACY_CATEGORY_ALIASES = {
    "restaurant": "food",
    "cafe": "food",
    "fast_food": "food",
    "dessert": "food",
    "bakery": "food",
    "juice": "food",
    "food_truck": "food",
    "outdoor": "nature",
    "other": "entertainment",
    "mall": "shopping",
    "museum": "heritage",
}


def normalize_category(raw_category, title="", description=""):
    normalized = str(raw_category or "").strip().lower()
    if normalized in {"culture", "heritage", "entertainment", "food", "shopping", "nature", "family", "events"}:
        return normalized
    if normalized in LEGACY_CATEGORY_ALIASES:
        return LEGACY_CATEGORY_ALIASES[normalized]

    haystack = f"{title} {description} {normalized}".lower()
    keyword_rules = [
        ("heritage", ("museum", "heritage", "historic", "fort", "palace", "souq")),
        ("events", ("event", "festival", "concert", "show", "season", "exhibition")),
        ("family", ("family", "kids", "children", "zoo", "playground", "aquarium")),
        ("nature", ("park", "garden", "wadi", "desert", "trail", "nature")),
        ("shopping", ("mall", "shopping", "market", "boutique", "store")),
        ("culture", ("culture", "art", "gallery", "library", "theatre", "theater")),
        ("food", ("restaurant", "cafe", "coffee", "food", "dining", "bakery")),
        ("entertainment", ("cinema", "game", "fun", "amusement", "escape room")),
    ]
    for category, keywords in keyword_rules:
        if any(keyword in haystack for keyword in keywords):
            return category
    return "events"


def set_tourism_defaults(apps, schema_editor):
    Event = apps.get_model("events", "Event")

    for event in Event.objects.all().iterator():
        normalized_category = normalize_category(
            event.category,
            title=event.title,
            description=event.description,
        )
        event.category = normalized_category
        if not event.source:
            event.source = "Legacy dataset"
        if normalized_category in {"heritage", "events"}:
            event.tourism_relevance = max(event.tourism_relevance or 0, 5)
        elif normalized_category in {"culture", "family", "nature"}:
            event.tourism_relevance = max(event.tourism_relevance or 0, 4)
        else:
            event.tourism_relevance = max(event.tourism_relevance or 0, 3)
        event.is_active = True if event.is_active is None else event.is_active
        event.save(
            update_fields=["category", "source", "tourism_relevance", "is_active"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tourism_relevance',
            field=models.PositiveSmallIntegerField(default=3, help_text='Simple tourism relevance score from 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('culture', 'Culture'), ('heritage', 'Heritage'), ('entertainment', 'Entertainment'), ('food', 'Food'), ('shopping', 'Shopping'), ('nature', 'Nature'), ('family', 'Family'), ('events', 'Events')], db_index=True, max_length=50),
        ),
        migrations.RunPython(set_tourism_defaults, migrations.RunPython.noop),
    ]
