# Generated by Django 6.0 on 2026-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userpreferences_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='preferred_language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='en', max_length=5),
        ),
    ]
