# Generated by Django 6.0 on 2026-04-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userpreferences_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="min_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Minimum place rating (e.g. 3.5, 4.0, 4.5). Null means no filter.",
                max_digits=2,
                null=True,
            ),
        ),
    ]
