# Generated by Django 6.0 on 2026-04-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_event_end_date_and_more"),
        ("daily_plan", "0002_dailyplan_unique_user_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("activity", "Activity"),
                            ("lunch", "Lunch"),
                            ("evening", "Evening"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("manual", "Manual"),
                            ("replacement", "Replacement"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="daily_plan.dailyplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="dailyplanitem",
            constraint=models.UniqueConstraint(
                fields=("plan", "event"),
                name="unique_event_per_daily_plan_item",
            ),
        ),
    ]
